Replaced some default values and add feature to replace field name
vmware/fluent-plugin-vmware-loginsight pull request #21
Opened 2021-02-20 23:41 UTC by mardanyan

-Replaced scheme and port
Latest version by default configured get events only on SSL.
So make appropriate scheme and port changes.

-Added feature
Getting issue on filed name for event after running logs with below command
docker run --log-driver=fluentd --log-opt tag="docker.{{.ID}}" ubuntu echo 'Hello Fluentd!'
Generated logs has field with name `source` which is unacceptable by loginsight.
Added feature to rename field name with preferable one.
Configuration name is replace_field_name, which by default has following mapping
config_param :replace_field_name, :hash, default: {"source": "log_source"}, value_type: :string

2021-02-22 03:46 UTC, mohitevishal requested changes

2021-02-22 03:46 UTC, mohitevishal commented on lib/fluent/plugin/out_vmware_loginsight.rb
> +            # check if name of the key should be replaced
Please move this check above ln169

2021-02-22 03:46 UTC, mohitevishal commented on lib/fluent/plugin/out_vmware_loginsight.rb
> +            if @replace_field_name.key?(key.to_sym)
We've been using string instead of symbol for keys. Lets continue with that.

2021-02-22 03:46 UTC, mohitevishal commented on lib/fluent/plugin/out_vmware_loginsight.rb
> +              key = @replace_field_name[key.to_sym]
ditto

2021-02-22 03:46 UTC, mohitevishal commented on lib/fluent/plugin/out_vmware_loginsight.rb
> +      config_param :scheme, :string, :default => 'https'
Though we should use `https`,  changing default would affect some users. We haven't published release notes, perhaps we can do that, or we can delay this change for some other day.

2021-03-30 01:25 UTC, closed without merging

2021-03-30 01:25 UTC, mardanyan commented
New one will be created